config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get 'pages/about' => 'pages#about'

  get 'books/search' => 'books#search'

  get 'signup' => 'users#new'



  resources :users
  resources :mybests

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord


      # プロパティの設定
    attr_accessor :title, :image_url, :url

    def initialize(title, image_url, url)
      @title = title
      @image_url = image_url
      @url = url
    end


end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController


  def search
     if params[:keyword].present?
       #　デバックログ出力するために記述
       Amazon::Ecs.debug = true

       # Amazon::Ecs::Responceオブジェクトの取得
       books = Amazon::Ecs.item_search(
         params[:keyword],
         search_index:  'All',
         dataType: 'script',
         response_group: 'ItemAttributes, Images',
         country:  'jp',
        #  power: "Not kindle"
       )

       # 本のタイトル,画像URL, 詳細ページURLの取得
       @books = []
       books.items.each do |item|
         book = Book.new(
           item.get('ItemAttributes/Title'),
           item.get('LargeImage/URL'),
           item.get('DetailPageURL'),
         )
         @books << book
       end
     end
   end





end

app/controllers/mybests_controller.rb
class MybestsController < ApplicationController


  def new
  end




  def index

  end



end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


  def home
  end


  def about
      
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])

  end

  def create

    @user = User.new(user_params)
      if @user.save
        # log_in @user
        redirect_to @user

      else
        render "new"
      end

  end


  def new
    @user = User.new

  end


private

def user_params
  params.require(:user).permit(:email,:password, :password_confirmation)


end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mybests_helper.rb
module MybestsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book_list.html.erb
<% if @books.present? %>
  <% @books.each do |book| %>
    <div class="list">
      <%= link_to (image_tag(book.image_url, style: "width: 70px;height: 100px;display: inline-block;")), book.url, target: "blank" %>
      <%= book.title %>
    </div>
  <% end %>
<% end %>

app/views/books/search.html.erb
<%= render 'shared/header' %>


<div class="container">


    <div class='content'>
      <div id="search-box">
        <%= form_tag('/books/search', method: :get) do %>
            <%= text_field_tag :book, "",  id: "book_search", name: "keyword", placeholder: "キーワードを打ち込んでください", style: "width: 200px;"%><button title="検索" type="submit">検索</button>
        <% end %>
      </div>
      <h2>検索結果</h2>
      <div id='book_list'>
       <%= render partial: 'book_list' %>
      </div>
    </div>

</div>

<%= render 'shared/footer' %>

app/views/books/search.js.erb
$("#book_list").html("<%= j(render 'book_list') %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>俺のベスト１０</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mybests/index.html.erb
<%= render 'shared/header' %>


index



<%= render 'shared/footer' %>

app/views/mybests/new.html.erb
<%= render 'shared/header' %>

<div class="container">
  <h1>ベスト１０を作る</h1>
</div>


<%= render 'shared/footer' %>

app/views/pages/about.html.erb
<%= render 'shared/header' %>

<div class="about-main">

  <div class="container">

    <h1>俺のベスト10とは？？？</h1>
    <p class="mybest-english">- my best 10 -</p>

    <div class="about-contents">

        例えば、、俺のベスト<span>「アルバム」</span>ランキング<br><br>
        例えば、、俺のベスト<span>「本」</span>ランキング<br><br>
        例えば、、俺のベスト<span>「映画」</span>ランキング。<br><br>
        例えば、、俺のベスト<span>「ドラマ」</span>ランキング。<br><br><br><br>
        自分だけのオリジナルランキングを作って、みんなに披露しよう！！！<br><br>
    </div>


    <div class="about-btn">
      <%= link_to 'ランキングを作る', new_mybest_path %>
    </div>

  </div>
</div>



<%= render 'shared/footer' %>

app/views/pages/home.html.erb
<%= render 'shared/header' %>

<div class="home-main">

    <h1 class="top-title">俺のベスト10</h1>
    <%= link_to '始める', new_mybest_path %>

</div>


<%= render 'shared/footer' %>

app/views/shared/_footer.html.erb
<!-- <footer>footer</footer> -->

app/views/shared/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to '俺のベスト10', root_path, {:class => 'navbar-brand'} %>
    </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to '俺のベストとは？', pages_about_path %></li>
          </ul>


      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'みんなのベスト10', mybests_path %></li>

        <li><%= link_to 'ベスト10を作る', books_search_path %></li>
        <li><a href="#">ログイン</a></li>
        <li><%= link_to 'サインアップ', signup_path %></li>        

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">アカウント <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>


    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<%= render 'shared/header' %>

<div class="container">


<h1>sing-up</h1>


    <%= form_for(@user) do |f| %>

    <%= f.label :email %><br>
    <%= f.text_field :email %><br>

    <%= f.label :password, "パスワード" %><br>
    <%= f.password_field :password %><br>

    <%= f.label :password_confirmation, "パスワード再入力" %><br>
    <%= f.password_field :password_confirmation %><br>

    <%= f.submit "登録する" %>



<% end %>



</div>
<%= render 'shared/footer' %>

app/views/users/show.html.erb
<%= render 'shared/header' %>

<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

<%= @user.email %>



<%= render 'shared/footer' %>